agentName: mmagent01
envName: dev
agentRuntimeName: mmagent01_dev
imageRepo: 229560443702.dkr.ecr.us-west-2.amazonaws.com
tag: c016c05a8a3d87189a03e0c9f01e57b04e6aabe6
roleArn: arn:aws:iam::229560443702:role/service-role/AmazonBedrockAgentCoreRuntimeDefaultServiceRole
cloudWatchLogTailRoleArn: arn:aws:iam::229560443702:role/cnoe-refl-cw-logs-tail
agentRuntimeID: demoagent002_dev-P57qHb5iUO
region: us-west-2



environmentVariables:
  DISABLE_ADOT_OBSERVABILITY: "true"
  # OPENAI_API_SECRET: "tenant02/mmagent01/api_key"
  AGENT_NAME: mmagent01_dev
  AGENT_ENV: Dev
  LANGFUSE_API_SECRET: prod/langfuse

secrets:
  - name: openapi_key
    vault:
      path: tenant02/mmagent01
      key: api_key
    awsSecretManager:
      key: "tenant02/mmagent01/api_key"
    
